feat: darken s:palette.comment and s:palette.fg to make it more friendly to eyes
ulwlu/elly.vim pull request #20
Opened 2020-12-18 12:32 UTC by shiyanhui

Hi,

Recently I'm looking for an alternative to solarized, and I found elly.vim. It's comfortable and I like it very much.  But one problem is that the foreground color is too bright which will hurt eyes heavily. So I change it a bit.

2020-12-18 20:32 UTC, ulwlu requested changes
Hi @shiyanhui , Thank you so much for your PR!
I think this PR makes sense very much because a similar issue has been posted https://github.com/ulwlu/elly.vim/issues/13 a few day agos by @d86leader.

At that time I decided not to change, but now, I realized many people feel same way. 
I should merge this PR.

Before merging, would you check my change-suggestions below?
I'd like to adjust the color palette along with **less red, more green** and **complementary each other**.

Theme will be like this.
<img width="1440" alt="ss 4" src="https://user-images.githubusercontent.com/41639488/102659168-4c053980-41bc-11eb-836b-7dffd1b3a8d0.png">

2020-12-18 20:32 UTC, ulwlu commented on colors/elly.vim
> +let s:palette.comment   = "#5A5A5A"
```suggestion
let s:palette.comment   = "#545759"
```

2020-12-18 20:33 UTC, ulwlu commented on colors/elly.vim
> +let s:palette.fg        = "#9A9A9A"
```suggestion
let s:palette.fg        = "#999FA1"
```

2020-12-19 05:35 UTC, shiyanhui commented on colors/elly.vim
> +let s:palette.comment   = "#5A5A5A"
I think it's ok to change comment to #545759.

2020-12-19 05:36 UTC, shiyanhui commented on colors/elly.vim
> +let s:palette.fg        = "#9A9A9A"
It's still a little bright but can be acceptable.

2020-12-19 06:04 UTC, ulwlu approved these changes
Thank you very much! This is really good turning of this theme.
Merging.

2020-12-19 06:04 UTC, merged